'use strict';
window.Game={canvas:null,ctx:null,run:null,time:0,last:0,angle:0,effects:[],bullets:[],enemies:[],w:800,h:400,callback:null,frame:0,
init(canvas,callback){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.callback=callback;new ResizeObserver(()=>this.resize()).observe(canvas);this.resize();requestAnimationFrame(t=>this.loop(t));},
resize(){let r=this.canvas.getBoundingClientRect();if(!r.width||!r.height)return;let ow=this.w,oh=this.h;this.w=r.width;this.h=r.height;let d=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.round(this.w*d);this.canvas.height=Math.round(this.h*d);this.ctx.setTransform(d,0,0,d,0,0);for(let e of this.enemies){e.x*=this.w/ow;e.y*=this.h/oh;}for(let b of this.bullets){b.x*=this.w/ow;b.y*=this.h/oh;}},
newRun(test=false,wave=1){this.enemies=[];this.bullets=[];this.effects=[];let m=test?[0,0,0,0]:Store.data.meta;this.run={test,wave,completed:wave-1,gold:50+m[3]*15,runes:0,up:[0,0,0,0],meta:[...m],hp:100+m[1]*20,kills:0,answered:0,attempts:0,firstCorrect:0,used:[],hintCount:0,elapsed:0,state:'staging',speed:1,visualLevel:0,upgradeFlash:0,upgradeType:0,spawned:0,total:0,spawnClock:0,fireClock:0,earned:0,settled:false,shield:0,combo:0};return this.run;},
stats(){let r=this.run,m=r.meta,u=r.up;return {damage:12+m[0]*3+u[0]*6,rate:1.25+u[1]*.28,maxHP:100+m[1]*20+u[2]*30,regen:.35+m[2]*.3+u[3]*.65,range:Math.min(this.w,this.h)*.43};},
cap(){return Math.min(12,1+Math.floor(this.run.runes/2));},cost(i){return Math.ceil(CFG.upgrades[i].base*Math.pow(1.38,this.run.up[i]));},
buy(i){let r=this.run;if(!r||r.settled||!['combat','ready','paused'].includes(r.state))return false;let cost=this.cost(i);if(r.up[i]>=this.cap()||r.gold<cost)return false;r.gold-=cost;r.up[i]++;if(i===1)r.fireClock=Math.min(r.fireClock,1/this.stats().rate);if(i===2)r.hp=Math.min(this.stats().maxHP,r.hp+30);r.visualLevel++;r.upgradeFlash=1.6;r.upgradeType=i;this.burst(this.w/2,this.h/2,['#ffce73','#b197ff','#85c9ff','#82f4c6'][i],32);this.callback('buy',i);return true;},
waveProfile(wave){let d=CFG.difficulty;return {hp:d.hpBase+wave*d.hpPerWave,speed:1+wave*d.speedPerWave,damage:d.damageBase+wave*d.damagePerWave,interval:Math.max(d.spawnMin,d.spawnBase-wave*d.spawnPerWave),count:6+wave*2+Math.floor(wave/3)+(wave%3===0?1:0)};},
startWave(){let r=this.run;if(!r||r.settled)return;r.state='combat';r.spawned=0;r.total=this.waveProfile(r.wave).count;r.spawnClock=.7;r.fireClock=0;this.enemies=[];this.bullets=[];AudioFX.play(Math.floor((r.wave-1)/3));},
spawn(){let r=this.run,region=Math.floor((r.wave-1)/3),idx=r.spawned,ang=Math.random()*Math.PI*2;if(region===1)ang=(idx%2?0:Math.PI)+Math.random()*.7-.35;if(region===2)ang=(Math.floor(idx/4)%4)*Math.PI/2+Math.random()*.45;let dx=Math.cos(ang),dy=Math.sin(ang),dist=Math.min((this.w/2+22)/Math.max(.001,Math.abs(dx)),(this.h/2+22)/Math.max(.001,Math.abs(dy)));let boss=r.wave%3===0&&idx===r.total-1,pools=[['slime','bat','beetle'],['bat','spider','wraith','beetle'],['golem','hound','spider','slime'],['wraith','hound','golem','bat','beetle','spider','slime']],kind=boss?'boss':pools[region][idx%pools[region].length],m=CFG.monsters[kind];let profile=this.waveProfile(r.wave),elite=!boss&&r.wave>=CFG.difficulty.eliteFrom&&idx%CFG.difficulty.eliteEvery===CFG.difficulty.eliteEvery-1,armor=Math.min(.3,(kind==='golem'?.15:kind==='beetle'?.1:kind==='boss'?.08:0)+(elite?.08:0));let hp=Math.round((17+r.wave*7)*m.hp*profile.hp*(elite?CFG.difficulty.eliteHP:1));this.enemies.push({x:this.w/2+dx*dist,y:this.h/2+dy*dist,hp,max:hp,speed:(10+r.wave*.9)*m.speed*profile.speed*Math.min(1,Math.min(this.w,this.h)/460),kind,size:m.size*(elite?1.18:1),damage:m.damage*profile.damage*(elite?CFG.difficulty.eliteDamage:1),gold:Math.round(m.gold*(elite?1.5:1)),elite,armor,attackPeriod:kind==='boss'?.9:1,attack:0,phase:0,seed:idx*.7});r.spawned++;},
step(dt){let r=this.run;if(!r||r.state!=='combat')return;let st=this.stats();r.elapsed+=dt;r.hp=Math.min(st.maxHP,r.hp+st.regen*dt);r.shield=Math.max(0,r.shield-dt);r.spawnClock-=dt;if(r.spawned<r.total&&r.spawnClock<=0){this.spawn();r.spawnClock=this.waveProfile(r.wave).interval;}let cx=this.w/2,cy=this.h/2,target=null,nearest=Infinity;
for(let e of this.enemies){let dx=cx-e.x,dy=cy-e.y,d=Math.hypot(dx,dy);if(e.kind==='boss'&&r.wave===12){let phase=e.hp/e.max<.34?2:e.hp/e.max<.67?1:0;if(phase>e.phase){e.phase=phase;this.callback('boss',phase);for(let j=0;j<4;j++){let a=j*Math.PI/2;this.enemies.push({x:e.x+Math.cos(a)*35,y:e.y+Math.sin(a)*35,hp:90,max:90,speed:32*Math.min(1,Math.min(this.w,this.h)/460),kind:'bat',size:11,damage:7,gold:8,armor:0,attack:0,phase:0,seed:j});}}}if(e.kind==='boss'&&r.wave!==12&&e.hp<=e.max*.5&&e.phase===0){e.phase=1;this.callback('rage');}if(d>27+e.size){let speed=e.speed*(e.kind==='boss'?1+e.phase*.3:1);e.x+=dx/d*speed*dt;e.y+=dy/d*speed*dt;}else{e.attack-=dt;if(e.attack<=0){r.hp-=e.damage*(e.kind==='boss'?1+e.phase*.15:1)*(r.shield>0?.5:1);e.attack=e.attackPeriod??1;this.burst(cx,cy,'#ff839c',6);AudioFX.hit();}}if(d<=st.range&&d<nearest){target=e;nearest=d;}}
r.fireClock-=dt;if(target){this.angle=Math.atan2(target.y-cy,target.x-cx);if(r.fireClock<=0){this.bullets.push({x:cx,y:cy-8,target,damage:st.damage,ttl:2});r.fireClock=1/st.rate;AudioFX.shot();}}
for(let i=this.bullets.length-1;i>=0;i--){let b=this.bullets[i];b.ttl-=dt;if(b.ttl<=0||b.target.hp<=0||!this.enemies.includes(b.target)){this.bullets.splice(i,1);continue;}let dx=b.target.x-b.x,dy=b.target.y-b.y,d=Math.hypot(dx,dy),speed=430;if(d<speed*dt+b.target.size){b.target.hp-=b.damage*(1-(b.target.armor||0));this.burst(b.target.x,b.target.y,'#99ffe4',4);this.bullets.splice(i,1);}else{b.x+=dx/d*speed*dt;b.y+=dy/d*speed*dt;}}
for(let i=this.enemies.length-1;i>=0;i--){let e=this.enemies[i];if(e.hp<=0){r.kills++;r.gold+=e.gold??8;this.burst(e.x,e.y,CFG.regions[Math.floor((r.wave-1)/3)].enemy,12);this.enemies.splice(i,1);this.callback('economy');}}
if(r.hp<=0){r.hp=0;r.state='over';AudioFX.stop();this.callback('over');return;}if(r.spawned===r.total&&!this.enemies.length){r.completed=r.wave;r.state='between';AudioFX.stop();this.callback('waveClear');}},
burst(x,y,color,count){if(this.effects.length>220)return;for(let i=0;i<count;i++){let a=Math.random()*Math.PI*2,s=20+Math.random()*70;this.effects.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.4,color});}},
advance(dt){let r=this.run;if(!r||r.state!=='combat')return;let remaining=dt*r.speed;while(remaining>0&&r.state==='combat'){let h=Math.min(remaining,1/120);this.step(h);remaining-=h;}},
loop(t){let dt=Math.min((t-this.last)/1000||0,.04);this.last=t;this.time=t/1000;if(this.run){this.advance(dt);if(['combat','ready','paused'].includes(this.run.state)){this.run.upgradeFlash=Math.max(0,this.run.upgradeFlash-dt);for(let i=this.effects.length-1;i>=0;i--){let p=this.effects[i];p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;if(p.life<=0)this.effects.splice(i,1);}}if(!document.hidden)this.draw();if(++this.frame%8===0)this.callback('hud');}else if(!document.hidden){Visual.showcase(this.time);}requestAnimationFrame(x=>this.loop(x));},
draw(){let c=this.ctx,w=this.w,h=this.h,r=this.run;if(!r)return;let rg=CFG.regions[Math.floor((r.wave-1)/3)],cx=w/2,cy=h/2,st=this.stats(),region=Math.floor((r.wave-1)/3);c.clearRect(0,0,w,h);let bg=c.createRadialGradient(cx,cy,10,cx,cy,w*.65);bg.addColorStop(0,rg.bg);bg.addColorStop(1,'#0b1020');c.fillStyle=bg;c.fillRect(0,0,w,h);
// Hand-drawn procedural scenery, with a distinct layout in each biome.
c.strokeStyle=rg.color+'0c';c.lineWidth=1;for(let x=0;x<w;x+=40){c.beginPath();c.moveTo(x,0);c.lineTo(x,h);c.stroke();}for(let y=0;y<h;y+=40){c.beginPath();c.moveTo(0,y);c.lineTo(w,y);c.stroke();}
for(let i=0;i<18;i++){let x=(i*137+31)%w,y=(i*83+51)%h;if(Math.hypot(x-cx,y-cy)<90)continue;c.save();c.translate(x,y);c.fillStyle=rg.color+'18';c.strokeStyle=rg.color+'28';if(region===0){c.beginPath();c.moveTo(0,-13);c.lineTo(7,0);c.lineTo(0,13);c.lineTo(-7,0);c.closePath();c.fill();c.stroke();}else if(region===1){c.rotate(i);c.strokeRect(-7,-16,14,32);c.fillRect(-6,-15,12,30);}else if(region===2){c.beginPath();c.moveTo(-18,8);c.lineTo(0,-8);c.lineTo(13,10);c.lineTo(24,-5);c.stroke();}else{c.beginPath();c.arc(0,0,9+Math.sin(this.time+i)*2,0,7);c.stroke();}c.restore();}
c.setLineDash([6,8]);c.strokeStyle=rg.color+'45';c.beginPath();c.arc(cx,cy,st.range,0,Math.PI*2);c.stroke();c.setLineDash([]);c.fillStyle=rg.color+'06';c.fill();
Visual.tower(c,cx,cy,this.time,r.up,this.angle,r.upgradeFlash,r.upgradeType,r.shield>0);
for(let e of this.enemies)Visual.enemy(c,e,this.time,region);
for(let b of this.bullets){c.fillStyle='#e5fff4';c.shadowColor=rg.color;c.shadowBlur=13;c.beginPath();c.arc(b.x,b.y,3,0,7);c.fill();}c.shadowBlur=0;for(let p of this.effects){c.globalAlpha=Math.min(1,p.life*2);c.fillStyle=p.color;c.fillRect(p.x,p.y,3,3);}c.globalAlpha=1;if(r.state==='paused'){c.fillStyle='#08102266';c.fillRect(0,0,w,h);c.fillStyle='#f9e5b5';c.font='bold 24px system-ui';c.textAlign='center';c.fillText('ĐÃ TẠM DỪNG',cx,cy-85);c.textAlign='start';}}
};
